### ISSUE TITLE
設定ファイルにtomlを導入してみる

### ISSUE THREAD

**Issue by ieee0824** [jobtalk/pnzr#23]
jsonで定義するのは互換性のため維持する
試験的に使って採用するかは別途考える

**Comment by shota-suzuki** [comment]
jsonという形式を取りつつ、実は`$cluster`のようなjsonではパース出来ない構文を持っていたりする点は気になりました。
外部変数なりを扱えるようなDSLの方が適していると感じました

**Comment by ieee0824** [comment]
I solved it with that #82, so close it.
